### ISSUE TITLE
local.css issues

### ISSUE THREAD

**Issue by acabal** [scriptdaemon/washington-irving_the-sketch-book-of-geoffrey-crayon-gent#5]
- `p span.signature` selector should be just `.signature`; but it's also present in line 131 so you can remove the duplicate style
- Line 23 is not required since first-child p tags already have text-indent 0 inherited from `core.css`
- I don't think setting table width to 100% in line 8 is required; was there a specific problem you were selecting for there?
- To prevent personas in plays from wrapping, use this CSS:
````
td[epub|type~="z3998:persona"]{
	text-align: right;
	white-space: nowrap;
}
````
That will also obviate the need from setting table width and a 30% width on the persona cells. Check out The Importance of Being Earnest for complete play formatting patterns. (They are not yet written up in the manual I don't think but that's the model we're following until they are.)

**Comment by scriptdaemon** [comment]
All the styles related to the tables / personas were taken from an existing book on SE (though I don't remember which one). I've fixed with your changes and will use the book you suggest for this type of styling going forward.

**Comment by acabal** [comment]
Hmm, do you remember which one? It would be good to get them all consistent.
